### ISSUE TITLE
OutOfMemory exception when handling embedded fonts

### ISSUE THREAD

**Issue by fisch92** [m-abboud/FontVerter#9]
we found a rare case where Pdf2Dom throws an OutOfMemory exception when handling embedded fonts. The stack trace is

```
java.lang.OutOfMemoryError
  java.lang.AbstractStringBuilder.hugeCapacity(AbstractStringBuilder.java:161)
  java.lang.AbstractStringBuilder.newCapacity(AbstractStringBuilder.java:155)
  java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:125)
  java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
  java.lang.StringBuilder.append(StringBuilder.java:136)
  org.fit.pdfdom.PDFDomTree.createFontFace(PDFDomTree.java:564)
  org.fit.pdfdom.PDFDomTree.createFontFaces(PDFDomTree.java:551)
  org.fit.pdfdom.PDFDomTree.createGlobalStyle(PDFDomTree.java:533)
  org.fit.pdfdom.PDFDomTree.endDocument(PDFDomTree.java:176)
  org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:267)
  org.fit.pdfdom.PDFDomTree.createDOM(PDFDomTree.java:218)
  ...
The actual accumulation of data is probably happening in Fontverter at
      at org.mabb.fontverter.io.FontDataInputStream.readBytes(FontDataInputStream.java:56)
      at org.mabb.fontverter.opentype.OpenTypeParser.readTableDataEntries(OpenTypeParser.java:73)
      at org.mabb.fontverter.opentype.OpenTypeParser.parse(OpenTypeParser.java:47)
      at org.mabb.fontverter.opentype.OpenTypeParser.parse(OpenTypeParser.java:35)
      at org.mabb.fontverter.converter.PsType0ToOpenTypeConverter.getOtfFromDescendantFont(PsType0ToOpenTypeConverter.java:64)
      at org.mabb.fontverter.converter.PsType0ToOpenTypeConverter.convert(PsType0ToOpenTypeConverter.java:43)
      at org.mabb.fontverter.pdf.PdfFontExtractor.convertType0FontToOpenType(PdfFontExtractor.java:215)
      at org.fit.pdfdom.FontTable$Entry.loadType0TtfDescendantFont(FontTable.java:192)
      at org.fit.pdfdom.FontTable$Entry.getData(FontTable.java:145)
      at org.fit.pdfdom.FontTable$Entry.isEntryValid(FontTable.java:161)
      at org.fit.pdfdom.FontTable.addEntry(FontTable.java:48)
      at org.fit.pdfdom.PDFBoxTree.processFontResources(PDFBoxTree.java:385)
      at org.fit.pdfdom.PDFBoxTree.updateFontTable(PDFBoxTree.java:361)
      at org.fit.pdfdom.PDFDomTree.updateFontTable(PDFDomTree.java:544)
      at org.fit.pdfdom.PDFBoxTree.processPage(PDFBoxTree.java:206)
      at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:319)
      at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:266)
      at org.fit.pdfdom.PDFDomTree.createDOM(PDFDomTree.java:218)
```

You can reproduce the issue with e.g. this PDF file:
http://files.danfoss.com/technicalinfo/dila/17/FRCC.ED.VZH170BG.A6.22.pdf

We were checking the sourcecode and it looks like there is some broken offset in the table, pointing far beyond the actual byte array length (the offset deserialized is 1.338.484.881).

![nbjkppgdeodcjhhn](https://user-images.githubusercontent.com/17930104/41089697-c29570fa-6a42-11e8-8389-a46c71fa206f.png)

In FontDataInputStream then an array of the length 1.594.834.165 bytes is allocated. Then the method tries to read the data from the stream and receives every time a -1 as result (because the stream is at EoF).

    ```
public byte[] readBytes(int length) throws IOException {
        byte[] bytes = new byte[length];
        for (int i = 0; i < bytes.length; i++)
            bytes[i] = (byte) in.read();
        return bytes;
    }

```
This long array then later on causes issues in Pdf2Dom.

We propose a hotfix that introduces some range check into the readBytes() method, e.g.
    ```
public byte[] readBytes(int length) throws IOException {
        if (in.available() == 0)
            return new byte[0];
        byte[] bytes = new byte[length];
        for (int i = 0; i < bytes.length; i++)
        {
             byte b = (byte) in.read();
            if (b>-1)
                bytes[i] = b;
            else
                return Arrays.copyOf(bytes, i);
        }
        return bytes;
    }
```

As OutOfMemory Exceptions are hard to deal with once they occured we would like to see a fix for this soon.

Have a nice day

**Comment by m-abboud** [comment]
Thank for the bug report will look at when I get home from work
